import type { Opportunity } from "@/types/opportunity";

const collectedAt = "2026-06-10T06:00:00.000Z";

export const sampleOpportunities: ReadonlyArray<Opportunity> = [
  {
    id: "daad-epos-2027",
    external_id: "daad-epos-2027",
    source_name: "manual",
    source_url: "https://www.daad.de/",
    official_url: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    title: "DAAD EPOS Development-Related Postgraduate Courses",
    organization: "DAAD",
    type: "scholarship",
    destination_country: "Germany",
    destination_city: null,
    is_remote: false,
    deadline: "2026-10-15T23:59:00.000Z",
    deadline_confirmed: true,
    funding_type: "full",
    monthly_stipend: 992,
    monthly_stipend_currency: "EUR",
    travel_covered: true,
    housing_covered: false,
    tuition_covered: true,
    visa_covered: null,
    insurance_covered: true,
    meals_covered: null,
    application_fee: false,
    required_nationality: null,
    age_min: null,
    age_max: null,
    required_level: "any",
    required_domains: ["software", "data", "development"],
    required_experience_years: null,
    required_languages: ["English"],
    required_documents: ["CV", "Motivation letter", "Transcripts", "Recommendation letter", "Language certificate"],
    raw_description: "DAAD scholarship route with monthly stipend, travel allowance and insurance for development-related programs.",
    summary: "Bourse allemande très forte si le diplôme national est obtenu avant la cohorte cible.",
    eligibility_notes: "La reconnaissance du diplôme après l'examen national de septembre 2026 reste le point critique.",
    risks: "Certains parcours exigent un diplôme déjà finalisé et une expérience professionnelle.",
    candidacy_angle: "Relier Benin Cyber Shield à la sécurité financière et au développement numérique au Bénin.",
    score: 90,
    score_breakdown: {
      funding_full: 30,
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 10,
      travel_covered: 5,
      housing_covered: 0,
      advanced_degree_required: -10
    },
    status: "priority",
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2026-10-16T00:00:00.000Z"
  },
  {
    id: "eiffel-excellence-2027",
    external_id: "eiffel-excellence-2027",
    source_name: "campus-france",
    source_url: "https://www.campusfrance.org/",
    official_url: "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
    title: "Eiffel Excellence Scholarship Program",
    organization: "Campus France",
    type: "scholarship",
    destination_country: "France",
    destination_city: null,
    is_remote: false,
    deadline: "2027-01-08T23:59:00.000Z",
    deadline_confirmed: true,
    funding_type: "full",
    monthly_stipend: 1181,
    monthly_stipend_currency: "EUR",
    travel_covered: true,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: null,
    insurance_covered: true,
    meals_covered: null,
    application_fee: false,
    required_nationality: null,
    age_min: null,
    age_max: 27,
    required_level: "masters",
    required_domains: ["software", "cybersecurity", "engineering"],
    required_experience_years: null,
    required_languages: ["French", "English"],
    required_documents: ["CV", "Academic transcripts", "Study project", "Passport"],
    raw_description: "French excellence scholarship submitted through host institutions for master's and doctoral tracks.",
    summary: "Bourse prestige avec allocation et voyage, mais candidature dépendante d'une admission par établissement français.",
    eligibility_notes: "Le candidat ne postule pas directement: une école française doit porter le dossier.",
    risks: "Le niveau master est prématuré avant la validation officielle de la licence nationale.",
    candidacy_angle: "Cibler une école française cyber/data et présenter Benin Cyber Shield comme projet de souveraineté numérique.",
    score: 72,
    score_breakdown: {
      funding_full: 30,
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      deadline_window: 10,
      travel_covered: 5,
      advanced_degree_required: -30
    },
    status: "analyzing",
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2027-01-09T00:00:00.000Z"
  },
  {
    id: "google-summer-of-code-2027",
    external_id: "gsoc-2027",
    source_name: "google",
    source_url: "https://summerofcode.withgoogle.com/",
    official_url: "https://summerofcode.withgoogle.com/",
    title: "Google Summer of Code Contributor Program",
    organization: "Google Open Source",
    type: "fellowship",
    destination_country: "Remote",
    destination_city: null,
    is_remote: true,
    deadline: "2027-04-02T18:00:00.000Z",
    deadline_confirmed: true,
    funding_type: "partial",
    monthly_stipend: 1500,
    monthly_stipend_currency: "USD",
    travel_covered: false,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: false,
    insurance_covered: false,
    meals_covered: false,
    application_fee: false,
    required_nationality: null,
    age_min: 18,
    age_max: null,
    required_level: "any",
    required_domains: ["software", "open source", "data"],
    required_experience_years: null,
    required_languages: ["English"],
    required_documents: ["Proposal", "GitHub profile", "Project links"],
    raw_description: "Remote open-source contribution program with stipend after accepted milestones.",
    summary: "Excellent match pour renforcer GitHub, expérience internationale et preuve de delivery logiciel.",
    eligibility_notes: "Choisir une organisation open-source compatible Python, web, sécurité ou data.",
    risks: "La sélection dépend fortement d'une proposition technique claire et de contributions avant candidature.",
    candidacy_angle: "Prouver la capacité à livrer avec FastAPI, React, Docker et un projet cyber concret.",
    score: 88,
    score_breakdown: {
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 10,
      funding_full: 0,
      travel_covered: 0,
      housing_covered: 0
    },
    status: "priority",
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2027-04-03T00:00:00.000Z"
  },
  {
    id: "mozilla-technology-fund-2026",
    external_id: "mozilla-tech-fund-2026",
    source_name: "mozilla",
    source_url: "https://foundation.mozilla.org/",
    official_url: "https://foundation.mozilla.org/en/what-we-fund/",
    title: "Mozilla Technology Fund Fellowship",
    organization: "Mozilla Foundation",
    type: "fellowship",
    destination_country: "Remote",
    destination_city: null,
    is_remote: true,
    deadline: "2026-08-30T23:59:00.000Z",
    deadline_confirmed: false,
    funding_type: "partial",
    monthly_stipend: 2500,
    monthly_stipend_currency: "USD",
    travel_covered: null,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: false,
    insurance_covered: null,
    meals_covered: false,
    application_fee: false,
    required_nationality: null,
    age_min: 18,
    age_max: null,
    required_level: "professional",
    required_domains: ["software", "cybersecurity", "internet health"],
    required_experience_years: 1,
    required_languages: ["English"],
    required_documents: ["CV", "Project proposal", "Portfolio", "References"],
    raw_description: "Technology fellowship style funding for public-interest internet and digital rights work.",
    summary: "Fellowship très aligné cyber/droits numériques, à vérifier car la deadline n'est pas confirmée.",
    eligibility_notes: "La preuve d'impact local et la qualité du projet comptent plus que le diplôme.",
    risks: "Deadline et conditions de financement doivent être confirmées sur l'appel officiel.",
    candidacy_angle: "Présenter Mobile Money fraud detection comme défense des utilisateurs vulnérables.",
    score: 76,
    score_breakdown: {
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      deadline_window: 10,
      unconfirmed_deadline: -10
    },
    status: "analyzing",
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: null
  },
  {
    id: "cern-technical-student-2026",
    external_id: "cern-technical-student-2026",
    source_name: "cern-careers",
    source_url: "https://careers.cern/",
    official_url: "https://careers.cern/",
    title: "CERN Technical Student Programme",
    organization: "CERN",
    type: "internship",
    destination_country: "Switzerland",
    destination_city: "Geneva",
    is_remote: false,
    deadline: "2026-07-29T12:00:00.000Z",
    deadline_confirmed: true,
    funding_type: "partial",
    monthly_stipend: 3407,
    monthly_stipend_currency: "CHF",
    travel_covered: true,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: true,
    insurance_covered: true,
    meals_covered: null,
    application_fee: false,
    required_nationality: null,
    age_min: 18,
    age_max: null,
    required_level: "undergrad",
    required_domains: ["software", "data", "engineering"],
    required_experience_years: null,
    required_languages: ["English", "French"],
    required_documents: ["CV", "Academic transcript", "Reference letter"],
    raw_description: "Technical student program for students in applied sciences, computing and engineering.",
    summary: "Stage payé exceptionnel pour crédibilité internationale et expérience software/data.",
    eligibility_notes: "Être inscrit comme étudiant pendant le stage et vérifier les conditions de durée.",
    risks: "Compétition forte; dossier académique et preuve de niveau technique nécessaires.",
    candidacy_angle: "Mettre en avant FastAPI, Docker, PostgreSQL et rigueur de cybersécurité appliquée.",
    score: 92,
    score_breakdown: {
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 10,
      travel_covered: 5,
      housing_covered: 0
    },
    status: "priority",
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2026-07-30T00:00:00.000Z"
  },
  {
    id: "afdb-ict-internship-2026",
    external_id: "afdb-ict-internship-2026",
    source_name: "afdb-careers",
    source_url: "https://www.afdb.org/en/about/careers",
    official_url: "https://www.afdb.org/en/about/careers/current-vacancies",
    title: "AfDB ICT and Digital Transformation Internship",
    organization: "African Development Bank",
    type: "internship",
    destination_country: "Côte d'Ivoire",
    destination_city: "Abidjan",
    is_remote: false,
    deadline: "2026-06-24T23:59:00.000Z",
    deadline_confirmed: true,
    funding_type: "partial",
    monthly_stipend: 700,
    monthly_stipend_currency: "USD",
    travel_covered: false,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: null,
    insurance_covered: null,
    meals_covered: false,
    application_fee: false,
    required_nationality: "African member countries",
    age_min: 18,
    age_max: 30,
    required_level: "undergrad",
    required_domains: ["software", "ICT", "data"],
    required_experience_years: null,
    required_languages: ["English", "French"],
    required_documents: ["CV", "Proof of enrollment", "Motivation letter"],
    raw_description: "Internship for young African students in digital transformation and ICT support.",
    summary: "Très bon match régional, payé, proche culturellement, deadline courte.",
    eligibility_notes: "Ouvert aux pays membres africains; preuve d'inscription universitaire attendue.",
    risks: "Deadline proche et financement exact à confirmer avant priorisation totale.",
    candidacy_angle: "Positionner Benin Cyber Shield comme produit fintech/cyber utile au développement africain.",
    score: 81,
    score_breakdown: {
      monthly_stipend: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 0,
      unconfirmed_deadline: 0,
      travel_covered: 0
    },
    status: "applying",
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2026-06-25T00:00:00.000Z"
  },
  {
    id: "cisco-netacad-cybersecurity-2026",
    external_id: "cisco-netacad-cybersecurity-2026",
    source_name: "cisco-netacad",
    source_url: "https://www.netacad.com/",
    official_url: "https://www.netacad.com/courses/cybersecurity",
    title: "Cisco Networking Academy Cybersecurity Training",
    organization: "Cisco Networking Academy",
    type: "training",
    destination_country: "Remote",
    destination_city: null,
    is_remote: true,
    deadline: null,
    deadline_confirmed: false,
    funding_type: "partial",
    monthly_stipend: null,
    monthly_stipend_currency: "USD",
    travel_covered: false,
    housing_covered: false,
    tuition_covered: true,
    visa_covered: false,
    insurance_covered: false,
    meals_covered: false,
    application_fee: false,
    required_nationality: null,
    age_min: 13,
    age_max: null,
    required_level: "any",
    required_domains: ["cybersecurity", "networking"],
    required_experience_years: null,
    required_languages: ["English", "French"],
    required_documents: ["Email account", "Learning profile"],
    raw_description: "Online cybersecurity training track with free or partner-funded learning paths.",
    summary: "Formation utile et gratuite/financée, mais pas une opportunité de voyage.",
    eligibility_notes: "À utiliser comme renforcement de profil, pas comme priorité mobilité.",
    risks: "Pas d'allocation mensuelle ni voyage; financement exact dépend du partenaire local.",
    candidacy_angle: "Compléter le profil cyber avant des candidatures plus sélectives.",
    score: 61,
    score_breakdown: {
      global_nationality: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 10,
      unconfirmed_deadline: -10,
      monthly_stipend: 0
    },
    status: "new",
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: null
  },
  {
    id: "expired-unv-ict-specialist-2026",
    external_id: "unv-ict-specialist-2026",
    source_name: "untalent",
    source_url: "https://untalent.org/jobs/rss",
    official_url: "https://untalent.org/jobs/",
    title: "UN Volunteer ICT Support Specialist",
    organization: "United Nations Volunteers",
    type: "volunteer",
    destination_country: "Kenya",
    destination_city: "Nairobi",
    is_remote: false,
    deadline: "2026-05-20T23:59:00.000Z",
    deadline_confirmed: true,
    funding_type: "unknown",
    monthly_stipend: null,
    monthly_stipend_currency: "USD",
    travel_covered: null,
    housing_covered: null,
    tuition_covered: false,
    visa_covered: null,
    insurance_covered: null,
    meals_covered: null,
    application_fee: false,
    required_nationality: "Global applicants",
    age_min: 18,
    age_max: null,
    required_level: "professional",
    required_domains: ["ICT", "software"],
    required_experience_years: 1,
    required_languages: ["English"],
    required_documents: ["CV", "UNV profile"],
    raw_description: "Expired UNV ICT listing kept to validate archive and duplicate states.",
    summary: "Offre expirée conservée uniquement pour historique et apprentissage.",
    eligibility_notes: "Ne pas postuler; vérifier les prochaines ouvertures similaires.",
    risks: "Expirée, financement ambigu, et similaire à une autre fiche UNV déjà vue.",
    candidacy_angle: "Recycler la recherche pour une prochaine ouverture ICT UNV.",
    score: 35,
    score_breakdown: {
      technical_domain: 15,
      deadline_window: 0,
      monthly_stipend: 0
    },
    status: "archived",
    is_duplicate: true,
    duplicate_of_id: "unv-ict-support-prior-source",
    created_at: "2026-05-10T06:00:00.000Z",
    updated_at: "2026-05-21T00:00:00.000Z",
    collected_at: "2026-05-10T06:00:00.000Z",
    expires_at: "2026-05-21T00:00:00.000Z"
  }
];
