import type { Opportunity } from "@/types/opportunity";

const collectedAt = "2026-06-10T06:00:00.000Z";

export const sampleOpportunities: ReadonlyArray<Opportunity> = [
  {
    id: "daad-epos-2027",
    external_id: "daad-epos-2027",
    source_name: "manual",
    source_url: "https://www.daad.de/",
    official_url: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    title: "Cours postuniversitaires DAAD EPOS liés au développement",
    organization: "DAAD",
    type: "scholarship",
    destination_country: "Allemagne",
    destination_city: null,
    is_remote: false,
    deadline: "2026-10-15T23:59:00.000Z",
    deadline_confirmed: true,
    funding_type: "full",
    monthly_stipend: 992,
    monthly_stipend_currency: "EUR",
    travel_covered: true,
    housing_covered: false,
    tuition_covered: true,
    visa_covered: null,
    insurance_covered: true,
    meals_covered: null,
    application_fee: false,
    required_nationality: null,
    age_min: null,
    age_max: null,
    required_level: "any",
    required_domains: ["logiciel", "données", "développement"],
    required_experience_years: null,
    required_languages: ["Anglais"],
    required_documents: ["CV", "Lettre de motivation", "Relevés de notes", "Lettre de recommandation", "Certificat de langue"],
    raw_description: "Bourse DAAD avec allocation mensuelle, appui voyage et assurance pour des parcours liés au développement.",
    summary: "Bourse allemande très forte si le diplôme national est obtenu avant la cohorte cible.",
    eligibility_notes: "La reconnaissance du diplôme après l'examen national de septembre 2026 reste le point critique.",
    risks: "Certains parcours exigent un diplôme déjà finalisé et une expérience professionnelle.",
    candidacy_angle: "Relier Benin Cyber Shield à la sécurité financière et au développement numérique au Bénin.",
    score: 90,
    score_breakdown: {
      funding_full: 30,
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 10,
      travel_covered: 5,
      housing_covered: 0,
      advanced_degree_required: -10
    },
    status: "priority",
    isSaved: true,
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2026-10-16T00:00:00.000Z"
  },
  {
    id: "eiffel-excellence-2027",
    external_id: "eiffel-excellence-2027",
    source_name: "campus-france",
    source_url: "https://www.campusfrance.org/",
    official_url: "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
    title: "Bourse d'excellence Eiffel",
    organization: "Campus France",
    type: "scholarship",
    destination_country: "France",
    destination_city: null,
    is_remote: false,
    deadline: "2027-01-08T23:59:00.000Z",
    deadline_confirmed: true,
    funding_type: "full",
    monthly_stipend: 1181,
    monthly_stipend_currency: "EUR",
    travel_covered: true,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: null,
    insurance_covered: true,
    meals_covered: null,
    application_fee: false,
    required_nationality: null,
    age_min: null,
    age_max: 27,
    required_level: "masters",
    required_domains: ["logiciel", "cybersécurité", "ingénierie"],
    required_experience_years: null,
    required_languages: ["Français", "Anglais"],
    required_documents: ["CV", "Relevés de notes", "Projet d'études", "Passeport"],
    raw_description: "Bourse d'excellence française portée par un établissement d'accueil pour les parcours master et doctorat.",
    summary: "Bourse prestige avec allocation et voyage, mais candidature dépendante d'une admission par établissement français.",
    eligibility_notes: "Le candidat ne postule pas directement: une école française doit porter le dossier.",
    risks: "Le niveau master est prématuré avant la validation officielle de la licence nationale.",
    candidacy_angle: "Cibler une école française cyber/data et présenter Benin Cyber Shield comme projet de souveraineté numérique.",
    score: 72,
    score_breakdown: {
      funding_full: 30,
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      deadline_window: 10,
      travel_covered: 5,
      advanced_degree_required: -30
    },
    status: "analyzing",
    isSaved: false,
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2027-01-09T00:00:00.000Z"
  },
  {
    id: "google-summer-of-code-2027",
    external_id: "gsoc-2027",
    source_name: "google",
    source_url: "https://summerofcode.withgoogle.com/",
    official_url: "https://summerofcode.withgoogle.com/",
    title: "Programme contributeur Google Summer of Code",
    organization: "Google Open Source",
    type: "fellowship",
    destination_country: "À distance",
    destination_city: null,
    is_remote: true,
    deadline: "2027-04-02T18:00:00.000Z",
    deadline_confirmed: true,
    funding_type: "partial",
    monthly_stipend: 1500,
    monthly_stipend_currency: "USD",
    travel_covered: false,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: false,
    insurance_covered: false,
    meals_covered: false,
    application_fee: false,
    required_nationality: null,
    age_min: 18,
    age_max: null,
    required_level: "any",
    required_domains: ["logiciel", "open source", "données"],
    required_experience_years: null,
    required_languages: ["Anglais"],
    required_documents: ["Proposition technique", "Profil GitHub", "Liens de projets"],
    raw_description: "Programme de contribution open source à distance avec allocation après validation des étapes acceptées.",
    summary: "Excellent match pour renforcer GitHub, l'expérience internationale et la preuve de livraison logicielle.",
    eligibility_notes: "Choisir une organisation open source compatible Python, web, sécurité ou données.",
    risks: "La sélection dépend fortement d'une proposition technique claire et de contributions avant candidature.",
    candidacy_angle: "Prouver la capacité à livrer avec FastAPI, React, Docker et un projet cyber concret.",
    score: 88,
    score_breakdown: {
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 10,
      funding_full: 0,
      travel_covered: 0,
      housing_covered: 0
    },
    status: "priority",
    isSaved: true,
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2027-04-03T00:00:00.000Z"
  },
  {
    id: "mozilla-technology-fund-2026",
    external_id: "mozilla-tech-fund-2026",
    source_name: "mozilla",
    source_url: "https://foundation.mozilla.org/",
    official_url: "https://foundation.mozilla.org/en/what-we-fund/",
    title: "Programme Mozilla Technology Fund",
    organization: "Mozilla Foundation",
    type: "fellowship",
    destination_country: "À distance",
    destination_city: null,
    is_remote: true,
    deadline: "2026-08-30T23:59:00.000Z",
    deadline_confirmed: false,
    funding_type: "partial",
    monthly_stipend: 2500,
    monthly_stipend_currency: "USD",
    travel_covered: null,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: false,
    insurance_covered: null,
    meals_covered: false,
    application_fee: false,
    required_nationality: null,
    age_min: 18,
    age_max: null,
    required_level: "professional",
    required_domains: ["logiciel", "cybersécurité", "santé d'Internet"],
    required_experience_years: 1,
    required_languages: ["Anglais"],
    required_documents: ["CV", "Proposition de projet", "Portfolio", "Références"],
    raw_description: "Financement de type programme technologique pour des travaux d'intérêt public liés à Internet et aux droits numériques.",
    summary: "Programme très aligné cyber/droits numériques, à vérifier car l'échéance n'est pas confirmée.",
    eligibility_notes: "La preuve d'impact local et la qualité du projet comptent plus que le diplôme.",
    risks: "L'échéance et les conditions de financement doivent être confirmées sur l'appel officiel.",
    candidacy_angle: "Présenter Mobile Money fraud detection comme défense des utilisateurs vulnérables.",
    score: 76,
    score_breakdown: {
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      deadline_window: 10,
      unconfirmed_deadline: -10
    },
    status: "analyzing",
    isSaved: false,
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: null
  },
  {
    id: "cern-technical-student-2026",
    external_id: "cern-technical-student-2026",
    source_name: "cern-careers",
    source_url: "https://careers.cern/",
    official_url: "https://careers.cern/",
    title: "Programme étudiant technique du CERN",
    organization: "CERN",
    type: "internship",
    destination_country: "Suisse",
    destination_city: "Genève",
    is_remote: false,
    deadline: "2026-07-29T12:00:00.000Z",
    deadline_confirmed: true,
    funding_type: "partial",
    monthly_stipend: 3407,
    monthly_stipend_currency: "CHF",
    travel_covered: true,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: true,
    insurance_covered: true,
    meals_covered: null,
    application_fee: false,
    required_nationality: null,
    age_min: 18,
    age_max: null,
    required_level: "undergrad",
    required_domains: ["logiciel", "données", "ingénierie"],
    required_experience_years: null,
    required_languages: ["Anglais", "Français"],
    required_documents: ["CV", "Relevé de notes", "Lettre de référence"],
    raw_description: "Programme étudiant technique pour les profils en sciences appliquées, informatique et ingénierie.",
    summary: "Stage payé exceptionnel pour la crédibilité internationale et l'expérience logiciel/données.",
    eligibility_notes: "Être inscrit comme étudiant pendant le stage et vérifier les conditions de durée.",
    risks: "Compétition forte; dossier académique et preuve de niveau technique nécessaires.",
    candidacy_angle: "Mettre en avant FastAPI, Docker, PostgreSQL et rigueur de cybersécurité appliquée.",
    score: 92,
    score_breakdown: {
      monthly_stipend: 20,
      global_nationality: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 10,
      travel_covered: 5,
      housing_covered: 0
    },
    status: "priority",
    isSaved: true,
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2026-07-30T00:00:00.000Z"
  },
  {
    id: "afdb-ict-internship-2026",
    external_id: "afdb-ict-internship-2026",
    source_name: "afdb-careers",
    source_url: "https://www.afdb.org/en/about/careers",
    official_url: "https://www.afdb.org/en/about/careers/current-vacancies",
    title: "Stage BAD TIC et transformation numérique",
    organization: "Banque africaine de développement",
    type: "internship",
    destination_country: "Côte d'Ivoire",
    destination_city: "Abidjan",
    is_remote: false,
    deadline: "2026-06-24T23:59:00.000Z",
    deadline_confirmed: true,
    funding_type: "partial",
    monthly_stipend: 700,
    monthly_stipend_currency: "USD",
    travel_covered: false,
    housing_covered: false,
    tuition_covered: false,
    visa_covered: null,
    insurance_covered: null,
    meals_covered: false,
    application_fee: false,
    required_nationality: "Pays membres africains",
    age_min: 18,
    age_max: 30,
    required_level: "undergrad",
    required_domains: ["logiciel", "TIC", "données"],
    required_experience_years: null,
    required_languages: ["Anglais", "Français"],
    required_documents: ["CV", "Preuve d'inscription", "Lettre de motivation"],
    raw_description: "Stage pour jeunes étudiants africains en transformation numérique et support TIC.",
    summary: "Très bon match régional, payé, proche culturellement, deadline courte.",
    eligibility_notes: "Ouvert aux pays membres africains; preuve d'inscription universitaire attendue.",
    risks: "Échéance proche et financement exact à confirmer avant priorisation totale.",
    candidacy_angle: "Positionner Benin Cyber Shield comme produit fintech/cyber utile au développement africain.",
    score: 81,
    score_breakdown: {
      monthly_stipend: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 0,
      unconfirmed_deadline: 0,
      travel_covered: 0
    },
    status: "applying",
    isSaved: false,
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: "2026-06-25T00:00:00.000Z"
  },
  {
    id: "cisco-netacad-cybersecurity-2026",
    external_id: "cisco-netacad-cybersecurity-2026",
    source_name: "cisco-netacad",
    source_url: "https://www.netacad.com/",
    official_url: "https://www.netacad.com/courses/cybersecurity",
    title: "Formation cybersécurité Cisco Networking Academy",
    organization: "Cisco Networking Academy",
    type: "training",
    destination_country: "À distance",
    destination_city: null,
    is_remote: true,
    deadline: null,
    deadline_confirmed: false,
    funding_type: "partial",
    monthly_stipend: null,
    monthly_stipend_currency: "USD",
    travel_covered: false,
    housing_covered: false,
    tuition_covered: true,
    visa_covered: false,
    insurance_covered: false,
    meals_covered: false,
    application_fee: false,
    required_nationality: null,
    age_min: 13,
    age_max: null,
    required_level: "any",
    required_domains: ["cybersécurité", "réseau"],
    required_experience_years: null,
    required_languages: ["Anglais", "Français"],
    required_documents: ["Compte e-mail", "Profil d'apprentissage"],
    raw_description: "Parcours de formation en cybersécurité en ligne, gratuit ou financé par des partenaires.",
    summary: "Formation utile et gratuite/financée, mais pas une opportunité de voyage.",
    eligibility_notes: "À utiliser comme renforcement de profil, pas comme priorité mobilité.",
    risks: "Pas d'allocation mensuelle ni voyage; financement exact dépend du partenaire local.",
    candidacy_angle: "Compléter le profil cyber avant des candidatures plus sélectives.",
    score: 61,
    score_breakdown: {
      global_nationality: 20,
      technical_domain: 15,
      undergrad_level: 10,
      deadline_window: 10,
      unconfirmed_deadline: -10,
      monthly_stipend: 0
    },
    status: "new",
    isSaved: false,
    is_duplicate: false,
    duplicate_of_id: null,
    created_at: collectedAt,
    updated_at: collectedAt,
    collected_at: collectedAt,
    expires_at: null
  },
  {
    id: "expired-unv-ict-specialist-2026",
    external_id: "unv-ict-specialist-2026",
    source_name: "untalent",
    source_url: "https://untalent.org/jobs/rss",
    official_url: "https://untalent.org/jobs/",
    title: "Volontariat ONU spécialiste support TIC",
    organization: "Volontaires des Nations Unies",
    type: "volunteer",
    destination_country: "Kenya",
    destination_city: "Nairobi",
    is_remote: false,
    deadline: "2026-05-20T23:59:00.000Z",
    deadline_confirmed: true,
    funding_type: "unknown",
    monthly_stipend: null,
    monthly_stipend_currency: "USD",
    travel_covered: null,
    housing_covered: null,
    tuition_covered: false,
    visa_covered: null,
    insurance_covered: null,
    meals_covered: null,
    application_fee: false,
    required_nationality: "Ouvert international",
    age_min: 18,
    age_max: null,
    required_level: "professional",
    required_domains: ["TIC", "logiciel"],
    required_experience_years: 1,
    required_languages: ["Anglais"],
    required_documents: ["CV", "Profil VNU"],
    raw_description: "Offre VNU TIC expirée conservée pour valider les états d'archive et de doublon.",
    summary: "Offre expirée conservée uniquement pour historique et apprentissage.",
    eligibility_notes: "Ne pas postuler; vérifier les prochaines ouvertures similaires.",
    risks: "Expirée, financement ambigu, et similaire à une autre fiche UNV déjà vue.",
    candidacy_angle: "Recycler la recherche pour une prochaine ouverture TIC VNU.",
    score: 35,
    score_breakdown: {
      technical_domain: 15,
      deadline_window: 0,
      monthly_stipend: 0
    },
    status: "archived",
    isSaved: false,
    is_duplicate: true,
    duplicate_of_id: "unv-ict-support-prior-source",
    created_at: "2026-05-10T06:00:00.000Z",
    updated_at: "2026-05-21T00:00:00.000Z",
    collected_at: "2026-05-10T06:00:00.000Z",
    expires_at: "2026-05-21T00:00:00.000Z"
  }
];
